# Referenced from: https://stackoverflow.com/a/75414339

name: base-branch-check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - unlocked
      - enqueued
      - ready_for_review

jobs:
  base-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge is allowed
        if: github.base_ref == github.event.repository.default_branch && github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge to the ${{ github.event.repository.default_branch }} branch from the 'development' branch."
          exit 1
